title: Kestin Goforth
author: Kestin Goforth
email: kgoforth1503@gmail.com
keywords: TODO
description: >-
  TODO
baseurl: "/Kest.in"
url: kest.in

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/